### ISSUE TITLE
Display Text Documents with Named Entities

### ISSUE THREAD

**Issue by enpuyou** [Allegheny-Ethical-CS/GatorMiner#36]
**Context and feature:**
A salient feature would be allowing the display of text documents, either by students or by questions. Currently, most of the texts are only displayed in  `pandas` data frame, which is not very intuitive. 

**Proposed solution:**
The display could take a similar approach as [here](https://github.com/Allegheny-Mozilla-Fellows/textMining/blob/48d234e23c8222e4a2a70dcfaad7018ecd78c05a/streamlit_web.py#L627), although more details need to be worked out.

**Useful resources:**
[Visualizing the entity recognizer](https://spacy.io/usage/visualizers#ent)

**Additional context:**
![Display NER](https://user-images.githubusercontent.com/35606694/109445247-2f338080-7a0d-11eb-9f57-0bd0c670f605.png)

**Acceptance criteria:**
Having a separate page where the user can select an individual's reflection to run the entity recognizer on. When done so, it should show the complete reflection of the individual with its entities highlighted and named, as shown in the example under additional context.

**Comment by jjumadinova** [comment]
Solution needs more detail specified (what is the acceptance criteria?). Also, please add an estimate.
