### ISSUE TITLE
Implement file upload through Streamlit

### ISSUE THREAD

**Issue by noorbuchi** [Allegheny-Ethical-CS/GatorMiner#37]
Requiring the path of the file(s) to analyze can be annoying sometimes and could cause errors due to typos in the path or lack of instruction on whether or not to include file format. It's also inconvenient to repeat the process several times for multiple files in different directories. 

![Screenshot from 2021-02-28 21-37-38](https://user-images.githubusercontent.com/55197145/109445265-3c506f80-7a0d-11eb-9324-d4017488d810.png)

One way to significantly improve the user experience is to have an `upload file(s)` button that allows the user to simply click and select the files they would like to reference. The great thing is this functionality is already supported by Streamlit; the documentation and example of it can be found [here](https://docs.streamlit.io/en/stable/api.html#streamlit.file_uploader). 

Few things to consider while implementing this feature:
- The return type of this streamlit object and how to access the contents of the file
- The ability to upload multiple files at once
- Handling the wrong file formats being uploaded and showing appropriate error messages

**Comment by cheng-cs** [comment]
Team 2 is working on this issue.

**Comment by enpuyou** [comment]
@cheng-cs @ColemanKobe Thanks for taking on this issue. Please let us know if you have any question and update us with the solution your team plan to take to implement the uploader.
