### ISSUE TITLE
Failing Build in Travis CI Due to mdl

### ISSUE THREAD

**Issue by enpuyou** [Allegheny-Ethical-CS/GatorMiner#43]
**Describe the bug**
The Travis CI build is currently failing due to an error installing `mdl`

**Expected behavior**

**Screenshots**

```
ERROR:  Error installing mdl:
288	The last version of chef-utils (>= 0) to support your Ruby & RubyGems was 16.6.14. Try installing it with `gem install chef-utils -v 16.6.14` and then running the current command again
289	chef-utils requires Ruby version >= 2.6.0. The current ruby version is 2.5.3.105.
290The command "gem install mdl" failed and exited with 1 during .
```

**Additional context**
The issue is also addressed in #28. However, if #28 cannot be fixed and merged soon, it would be best if there is a quick fix to make the build passing temporarily.

**Comment by rachaelharris** [comment]
Assigning my group to this task

**Comment by rachaelharris** [comment]
assigning my group to this task

**Comment by noorbuchi** [comment]
Since the branch for this issue was recently merged and mdl is now installing and the Travis CI build is passing, I think this issue can be closed. Feel free to reopen it if something relating to mdl comes up.
