### ISSUE TITLE
[Team 1] File Upload

### ISSUE THREAD

**Issue by ColemanKobe** [Allegheny-Ethical-CS/GatorMiner#47]
I added this epic to the ZenHub roadmap to track the five-week span of the implementation of that epic. This epic is related to issue #37.

**Comment by enpuyou** [comment]
Hi @ColemanKobe, can you provide a description of the issue? Is it related to issue #37? Thank you for working on this!

**Comment by enpuyou** [comment]
> I added this epic to the ZenHub roadmap to track the five-week span of the implementation of that epic. This epic is related to issue #37.

@ColemanKobe thanks for the update! Is it possible for you to just turn #37 into an Epic issue and track the road map there? I think it's a bit confusing to create an Epic for only one issue, especially when #47 does not introduce any new information, and #37 haven't been added to this Epic.

One additional comment: is the file uploader feature complex enough to be counted as an Epic issue? Or is there a larger Epic that includes the implementation of #37?

Thanks again for working on this.
