### ISSUE TITLE
Frequencies of categories of words

### ISSUE THREAD

**Issue by hewittk** [Allegheny-Ethical-CS/GatorMiner#51]
**Context and feature:**
The professor and many students agree that it would be convenient to add the most frequent categories of words to the frequency analysis page to get a broader view of what is most frequently referenced in the assignments. 

**Proposed solution:**
Add a list of the top ~ten most relevant word categories below the graph of the most frequent words on the frequency analysis page, with a list of category names with the number of words of each respective category next to it's name in the rankings. Possibly use lists of words of different categories online or first build an algorithm where you can manually add the most common words to categories, and then add a feature to track uncategorized non stop words in reflections and allow GatorMiner collaborators to add to them over time.
 
**Useful resources:**
Useful resources that might help with the resolution of the issue.

**Additional context:**

**Comment by enpuyou** [comment]
@hewittk Thanks for creating the feature request. Just a clarification for students who might want to pick up this issue: What kind of "wordmcategories" do you particularly have in mind? Can you provide some examples of these categories?

**Comment by hewittk** [comment]
> @hewittk Thanks for creating the feature request. Just a clarification for students who might want to pick up this issue: What kind of "wordmcategories" do you particularly have in mind? Can you provide some examples of these categories?

@enpuyou I'm envisioning categories for different types and technical sectors of Computer Science (i.e. bioinformatics, Github, programming, Pipenv, testing) along with different categories of professional skills (i.e. teamwork, communication, agile development). Words would often fall into multiple categories.

**Comment by enpuyou** [comment]
> @enpuyou I'm envisioning categories for different types and technical sectors of Computer Science (i.e. bioinformatics, Github, programming, Pipenv, testing) along with different categories of professional skills (i.e. teamwork, communication, agile development). Words would often fall into multiple categories.

@hewittk That's a great idea, and I can see multiple ways to have this implemented. Please keep us updated in this issue tracker. 

One additional question: is this issue also partially related to #54? Tagging @kahesayn here.

**Comment by kahesayn** [comment]
@enpuyou The thing I proposed is similar to this, but not exactly. I feel like this issue is looking more into the technical and professional aspects of the reflections where I was thinking more of how the text were showing how the people were feeling about the lab. Some key words might be like "difficult, hard, easy, challenging..." and it would rank them based on the words used.
