### ISSUE TITLE
Implement and Improve Landing Page

### ISSUE THREAD

**Issue by caldwella2** [Allegheny-Ethical-CS/GatorMiner#60]
**Context and feature:**
There is no true need to see the instructions of how to run the program if the program is already running. It is repetitive and it does not add anything to the landing page that is needed. 

**Proposed solution:**
We want to create a new landing page to reduce redundancy generated by the README. The new landing page would be a new markdown file and it would display how to use the sample files as an example of how to use files with the program.  It also would show quick instructions further explaining how to use the tools provided by GatorMiner.

**Comment by enpuyou** [comment]
@caldwella2 Thanks for proposing the change! I completely agree with you on the current landing page being redundant and unnecessary. Perhaps include instructions on what each analyzer does? Sort of like what #59 is proposing? I think it might be a good idea for your team to reach out so to make sure the contribution it's not overlapping.

**Comment by jjumadinova** [comment]
Please include more detailed acceptance criteria, an estimate and assign it to a sprint if working on this issue for sprint 1.
