### ISSUE TITLE
Logic error in file upload method

### ISSUE THREAD

**Issue by ColemanKobe** [Allegheny-Ethical-CS/GatorMiner#64]
**Describe the bug**
When multiple assignments are loaded, in the word frequency section of GatorMiner, one assignment is completely blank.

**To Reproduce**
1. Click on File Upload
2. Click on Browse Files
3. Pick multiple files from one directory at once and click Open
4. Repeat 2 and 3 from another directory
5. Choose both assignments from "Select assignments below:"
6. Choose frequency analysis as the analysis mode

**Expected behavior**
What's supposed to happen is that all of the assignments have the top 25 words displayed.

**Screenshot**
However, only one assignment has those words.
![Bug](https://user-images.githubusercontent.com/54693573/113019753-ed9f0e00-914f-11eb-98de-33fa8414fff8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera GX
 - Version 10

**Additional context**
The file_uploader widget apparently doesn't allow you to choose all of the files from different directories at once, so that might be a path to a solution.

**Comment by enpuyou** [comment]
@ColemanKobe Thanks for raising the issue. I can confirm this bug also appears on my end. I guess it's safe to assume that #62 shouldn't be merged until this is resolved?
